// eslint-disable-next-line
const socketEvents = {
  connect: 'connect',
  connection: 'connection',
  disconnect: 'disconnect',
  typeStart: 'typing:start',
  typeEnd: 'typing:end',
  sendMessage: 'message:send',
  editMessage: 'message:edit',
  editMessageSuccess: 'message:edit:success',
  reactOnMessage: 'message:emoji',
  reactOnMessageSuccess: 'message:emoji:success',
  deleteMessage: 'message:delete',
  deleteMessageSuccess: 'message:delete:success',
  sendInvite: 'email:send',
  sendInviteResult: 'email:result',
  renderUsers: 'html:users',
  renderMessageHistory: 'html:message',
  renderMessage: 'html:message:add',
  saveFile: 'file:save',
  saveFileSuccess: 'file:save:success',
};
